### ISSUE TITLE
double reference vs double-deref

### ISSUE THREAD

**Issue by Ragnar-F** [AutoHotkey/AutoHotkeyDocs#298]
Language.htm says:
> The most common form of dynamic variable reference is called a _double reference_ or _double-deref_.

Shouldn't that be called a double **de**reference?

**Comment by Lexikos** [comment]
No. A variable reference can be passed to a function and not dereferenced. In that context, a dynamic variable reference would be a double reference, but only a single level **de**reference (from `%y%` to whatever variable is named within).

**Comment by Ragnar-F** [comment]
I still have problems understanding this sentence. Does it mean that for "double-deref" you can also say "double reference"? And if so, why is it not called "double-ref"?

**Comment by Lexikos** [comment]
I really don't see the problem. It says it can be called by these two names, and so it can. Don't read too much into it. There are surely many concepts throughout the documentation and forum that could be called all sorts of names that aren't used in practice. Who ever said that it *can't* be called a double-ref?

As I said before, whether `%x%` (which is "the most common form of dynamic variable reference") *dereferences* the variable depends on context. It is always a dynamic/double reference and only sometimes performs double-dereferencing. I'd guess that people usually don't care to make the distinction, and will call it by whatever term is more memorable or convenient.

I don't use "double dereference" because it is awkward to say and type, and "dereference" is formally a verb. "Deref" is an informal name that Chris gave to any variable reference. "Double-deref" is catchier and already in common use. I never cared to consider "double-ref" and don't see a good reason to replace the established terminology.

**Comment by Ragnar-F** [comment]
Thanks for the clarification.

> Don't read too much into it.

For the purpose of translation, I "need" to do this. This helps me decide how and whether to translate "double-deref" at all.
